USE master
GO
SET NOCOUNT ON
GO

IF EXISTS(SELECT TOP 1 1 FROM sys.databases WHERE name = 'DBCONTROLE')
BEGIN
	ALTER DATABASE DBCONTROLE SET RESTRICTED_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE DBCONTROLE
	PRINT 'BASE REMOVIDA'
END
GO

CREATE DATABASE DBCONTROLE ON PRIMARY
(
	NAME = 'DBCONTROLE_DATA', FILENAME = 'D:\DES120A\DBCONTROLE.MDF'
)
LOG ON
(
	NAME = 'DBCONTROLE_LOG', FILENAME = 'E:\DES120A\DBCONTROLE.LDF'
)
GO
PRINT 'BASE CRIADA'
GO

ALTER DATABASE DBCONTROLE SET RECOVERY SIMPLE
GO
PRINT 'RECOVERY ALTERADO PARA SIMPLE'
GO

ALTER DATABASE DBCONTROLE SET ALLOW_SNAPSHOT_ISOLATION ON
GO
PRINT 'PERMISSAO PARA CONSULTAS SNAPSHOT'
GO


USE DBCONTROLE
GO

CREATE USER scopus FOR LOGIN scopus
GO
PRINT 'USUARIO SCOPUS CRIADO'
GO

CREATE SCHEMA listagem AUTHORIZATION dbo
GO
PRINT 'SCHEMA LISTAGEM CRIADO'
GO
GRANT EXECUTE ON SCHEMA :: listagem TO scopus
GO
PRINT 'PERMISSAO PARA O USUARIO SCOPUS NO SCHEMA LISTAGEM'
GO

SET NOCOUNT OFF
GO